### ISSUE TITLE
getting started quick tour needs details

### ISSUE THREAD

**Issue by lukeis** [SeleniumHQ/docs#69]
my initial thought is we need separate ones for each client language binding and then also each browser needs a section on what you may need to download / configure to run with it. Thoughts? :)

needed to log this as a placeholder for a google code issue.
https://code.google.com/p/selenium/issues/detail?id=8327

**Comment by tarun3kumar** [comment]
Let me take it up. Would start sending pull requests once I have considerable work.

On a different note, do we use https://gitter.im/ or some other resource for doc only conversations? I am hesitant to use selenium-developer group for doc only conversations as it might distract selenium developers.

**Comment by andreastt** [comment]
selenium-developers@, the #selenium IRC channel, or Github issues would probably be the best places to do documentation discussions to include the right people.

**Comment by tarun3kumar** [comment]
I would like to submit incremental pull requests for it, here is the first pull request - https://github.com/SeleniumHQ/docs/pull/80

**Comment by tarun3kumar** [comment]
I seek opinions/suggestions on following - 
- "Getting Started With WebDriver" should be a subsection of main "WebDriver" section.
- Adding language tag before examples. Could be a simeple text like "java" "ruby" (any thing better??), Foldable examples would add to readability. "+java" would open java example, "+ruby" would open ruby example etc (or could be tabs of different language with java opened by default). Instead of having all the examples opened by default and make page look like Bible.
  In absence of this newbie with programming as well as selenium might be left confused, for example "Firefox" section on page https://seleniumhq.github.io/docs/wd.html#driver_requirements cites both java and ruby (is that ruby??) with out mentioning the languages.

**Comment by andreastt** [comment]
> "Getting Started With WebDriver" should be a subsection of main "WebDriver" section.

The thinking here was originally that _start.html_ would be a very brief introduction to the basics of WebDriver to get you started, and that _webdriver.html_ would be the corresponding full-text nitty-gritty “authoritative” documentation on the details surrounding WebDriver.

Does this make sense?

> Adding language tag before examples. Could be a simeple text like "java" "ruby" (any thing better??)

We already do this in a number of places by annotating the container with the language, for example `<pre class=java><code>…</code></pre>`. We can probably get by with adding some JS to fold the code examples. I’ve filed https://github.com/SeleniumHQ/docs/issues/81 about this.

**Comment by tarun3kumar** [comment]
> Does this make sense?

I yet find it out of sync but that might be just me :)

> We already do this in a number of places by...

Not an html/css expert but I tried and got following.  Default Java sample on page load -

![DefaultJavaSample](http://i.imgur.com/OASAriv.png)

Other language samples display when reader clicks on a specific language link -

![OtherLanguageSampleDisplayOnSelectionofTab](http://i.imgur.com/jWWHSWP.png)

[Source](http://stackoverflow.com/questions/3354279/default-target-with-css)

What is your opinion of this display?

**Comment by andreastt** [comment]
With regards to the chapter reorganisation, I suggest we write the content first and then re-evaluate.

The language selection looks great!

**Comment by tarun3kumar** [comment]
~~pull request for langaue section discussed above - https://github.com/SeleniumHQ/docs/pull/82
Very initial change to have an impression on how it would look like. Not using _fancy_ html/css framework leaves us with limited options but probably keeping doc simple would also encourage others to add more to it.~~

Updates: I closed the pull request as not comfortable with whole idea of tackling code examples in html, getting rid of encoding etc. Was there a specific reason to not use rst for writing doc line in existing doc?

Probably code examples other than java be writtem once pull request https://github.com/SeleniumHQ/docs/issues/81 is done.

**Comment by tarun3kumar** [comment]
New pull request - https://github.com/SeleniumHQ/docs/pull/83

Couple of questions - 
- With respect to Selenium RC, do we want to make it elaborate or just focus on a section about migrating from RC to Webdriver. How do we know if RC is still being used?
- I have mentioned dependencies to selenium version 2.53.1 but this requires version to be updated with each new selenium release. Is there a better approach to handle it, like having version updated automatically with new release of selenium

**Comment by andreastt** [comment]
I don't think we should spend any time documenting Selenium RC, other than potentially something about migration to WebDriver. But even that I consider a low priority.

We can replace "2.53.1" with something like "x.y.z" so we don't have to update it every time there's a new release.

**Comment by maeriens** [comment]
I see there is a small chat here about formatting - wanted to ask here instead of opening a new issue.
There are several commands shown that are meant to be written in a console.

 Should we prepend to them a '$' (dollar sign) like it's commonly done? 
(i.e. _java -jar selenium-server-standalone.jar -role node -hub http://localhost:4444_ 
would become
_$ java -jar selenium-server-standalone.jar -role node -hub http://localhost:4444_)

 This will remove things like the coloring added to the `<code>` tags (see the blue *java* word in [Configuration of node with JSON on Grid Page](https://seleniumhq.github.io/docs/grid.html#configuration_of_node_with_json)) and the [bold words in Start the Hub](https://seleniumhq.github.io/docs/grid.html#step_1_start_the_ub), that is taken from... Google's css? Not 100% sure where that comes from.

**Comment by diemol** [comment]
Fixed on new site, please head to https://github.com/SeleniumHQ/seleniumhq.github.io and raise a PR ther if needed.
